//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// состояние светофора для машин
	/// </summary>
	public enum LightStates : int
	{
		/// <summary>
		/// светофор отсутвует
		/// </summary>
		None,
		Red,
		Green,
	}
}
