//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// маршруты движения машин
	/// </summary>
	public enum Routes : int
	{
		Top = 1,
        Right = 2,
		Bottom = 3,
		Left = 4,
	}
}
