//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// возможные состояния машины по типу текущей выполняемой задачи
	/// </summary>
	public enum CarStates
	{
		/// <summary>
		/// движение к кольцу
		/// </summary>
		MoveToRing,
		/// <summary>
		/// въезд на кольцо
		/// </summary>
		EntryRing,
		/// <summary>
		/// выезд из кольца
		/// </summary>
		DepartRing,
		/// <summary>
		/// движение по кольцу к выезду
		/// </summary>
		MoveToDepart,
		DepartMap,
	}
}
