//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim
{
	using RoadRingSim.Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPaintTask 
	{
		Render Render { get;set; }

		/// <summary>
		/// отрисовка текущего шага перемещения объекта из CellFrom в CellTo
		/// </summary>
		/// <param name="Model">модель объекта, который визуализируем</param>
		void Paint(Object Model);

	}
}

