//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim
{
    using RoadRingSim.Core;
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Linq;
    using System.Text;

	public interface IPaintTask 
	{
        public Cell CellFrom;
        public Cell CellTo;
        public Point CurrentPos;
        public int CurrentStep;
        public int StepAmount;

		/// <summary>
		/// отрисовка текущего шага перемещения объекта из CellFrom в CellTo
		/// </summary>
		/// <param name="Model">модель объекта, который визуализируем</param>
		void Paint(Object Model);

	}
}

