//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim.Core.Domains
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum UserRoles : int
	{
		User = 1,
		ExtUser = 2,
		SuperUser = 3,
	}
}
