//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RoadRingSim.Core.Domains
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum DistrubutionLaws : int
	{
		Expon = 2,
		Normal = 1,
		Uniform = 3,
	}
}
